services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  B13\Collapse\:
    resource: '../Classes/*'

  B13\Collapse\EventListener\ModifyPageLayoutContentEventListener:
    tags:
      - name: event.listener
        identifier: 'paste-reference/backend/modify-page-layout-content'
