services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  B13\Collapse\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  B13\Collapse\PageModuleModifier:
    public: true
